export const set1 = [
  { key: "A", sol: "Ayyappanum Koshiyum", question: "A clash between a cop and a retired havildar" },
  { key: "B", sol: "Bangalore Days", question: "Three cousins move to a big city and discover life" },
  { key: "C", sol: "Charlie", question: "A free-spirited traveler inspires a woman’s journey" },
  { key: "D", sol: "Drishyam", question: "A man goes to extreme lengths to protect his family" },
  { key: "E", sol: "Ennu Ninte Moideen", question: "A tragic real-life love story" },
  { key: "F", sol: "Forensic", question: "A crime thriller involving a forensic expert" },
  { key: "G", sol: "Great Indian Kitchen", question: "A woman struggles against patriarchal norms" },
  { key: "H", sol: "Helen", question: "A survival story inside a freezer" },
  { key: "I", sol: "Ishq", question: "A couple faces moral policing at night" },
  { key: "J", sol: "Joseph", question: "A retired police officer investigates a mystery" },
  { key: "K", sol: "Kumbalangi Nights", question: "Story of four brothers in a coastal village" },
  { key: "L", sol: "Lucifer", question: "A political drama with a mysterious leader" },
  { key: "M", sol: "Minnal Murali", question: "A local tailor gains superhero powers" },
  { key: "N", sol: "Njan Prakashan", question: "A lazy man dreams of going abroad" },
  { key: "O", sol: "Operation Java", question: "Cyber crime investigations by tech enthusiasts" },
  { key: "P", sol: "Premam", question: "A man's different stages of love life" },
  { key: "Q", sol: "Queen", question: "A group of engineering students and their journey" },
  { key: "R", sol: "Rorschach", question: "A mysterious man searches for his missing wife" },
  { key: "S", sol: "Sudani from Nigeria", question: "A football player from abroad changes a village" },
  { key: "T", sol: "Thondimuthalum Driksakshiyum", question: "A theft case unfolds in a police station" },
  { key: "U", sol: "Uyare", question: "An acid attack survivor follows her dream of flying" },
  { key: "V", sol: "Virus", question: "Based on the Nipah virus outbreak in Kerala" },
  { key: "W", sol: "Winter", question: "A psychological thriller set in a cold hill station" },
  { key: "X", sol: "X (Experimental Malayalam Film)", question: "A placeholder for rare Malayalam movie starting with X" },
  { key: "Y", sol: "Yoddha", question: "A man travels abroad to rescue a child monk" },
  { key: "Z", sol: "Zachariayude Garbhinikal", question: "Story revolving around pregnant women and a doctor" }
];